//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sportski_klub.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Klub
    {
        public Klub()
        {
            this.Clanarina1 = new HashSet<Clanarina>();
            this.Sportas = new HashSet<Sportas>();
            this.Trener = new HashSet<Trener>();
        }
    
        public int ID { get; set; }
        public string ImeKluba { get; set; }
        public System.DateTime DatumOsnivanja { get; set; }
        public int OIB { get; set; }
        public double Clanarina { get; set; }
        public string Adresa { get; set; }
    
        public virtual ICollection<Clanarina> Clanarina1 { get; set; }
        public virtual ICollection<Sportas> Sportas { get; set; }
        public virtual ICollection<Trener> Trener { get; set; }
    }
}
