//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sportski_klub.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KLUB_Entities : DbContext
    {
        public KLUB_Entities()
            : base("name=KLUB_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Clanarina> Clanarina { get; set; }
        public DbSet<Klub> Klub { get; set; }
        public DbSet<Sportas> Sportas { get; set; }
        public DbSet<Trener> Trener { get; set; }
    }
}
