//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sportski_klub.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sportas
    {
        public Sportas()
        {
            this.Clanarina = new HashSet<Clanarina>();
        }
    
        public int ID { get; set; }
        public int KlubID { get; set; }
        public Nullable<int> TrenerID { get; set; }
        public string Ime { get; set; }
        public string Prezime { get; set; }
        public System.DateTime DatumRodenja { get; set; }
        public int OIB { get; set; }
        public string MjestoStanovanja { get; set; }
        public string Adresa { get; set; }
        public Nullable<System.DateTime> LijecnickiPregledVrijediDo { get; set; }
        public System.DateTime DatumUpisa { get; set; }
    
        public virtual ICollection<Clanarina> Clanarina { get; set; }
        public virtual Klub Klub { get; set; }
        public virtual Trener Trener { get; set; }
    }
}
