//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sportski_klub.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trener
    {
        public Trener()
        {
            this.Sportas = new HashSet<Sportas>();
        }
    
        public int ID { get; set; }
        public int KlubID { get; set; }
        public bool IsAdmin { get; set; }
        public string Ime { get; set; }
        public string Prezime { get; set; }
        public int OIB { get; set; }
        public string Adresa { get; set; }
        public string Username { get; set; }
        public string Lozinka { get; set; }
    
        public virtual Klub Klub { get; set; }
        public virtual ICollection<Sportas> Sportas { get; set; }
    }
}
